name: image_service
description: A service for storing and retrieving images
version: 0.0.1-dev.6
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.1
  dart_frog: ^1.1.0
  dart_frog_html: ^0.0.1
  hive_ce: ^2.15.0
  http: ^1.3.0
  image: ^4.5.4
  mime: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.13
  hive_ce_generator: ^1.9.3
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
